izvorniKod/GameEx/GameEx/Models/Rental.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GameEx.Models
{
    public class Rental
    {
        public string Id { get; set; }
        public string PlayerId { get; set; }
        public Player Player { get; set; }
        public string RenterId { get; set; }
        public string GameId { get; set; }
        public InventoryItem InventoryItem { get; set; }
        public bool IsReturned { get; set; }
        public DateTime DateOfRent { get; set; }
        public DateTime? DateOfReturn { get; set; }
    }
}

izvorniKod/GameEx/GameEx/ViewModels/RentalViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using GameEx.Models;

namespace GameEx.ViewModels
{
    public class RentalViewModel
    {
        public string Id { get; set; }
        public string PlayerId { get; set; }
        public Player Player { get; set; }
        public string RenterId { get; set; }
        public string GameId { get; set; }
        public InventoryItem InventoryItem { get; set; }
        public bool IsReturned { get; set; }
        [DataType(DataType.Date)]
        public DateTime DateOfRent { get; set; }
        [DataType(DataType.Date)]
        public DateTime? DateOfReturn { get; set; }
    }
}

izvorniKod/GameEx/GameEx/Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GameEx.Data;
using GameEx.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using GameEx.ViewModels;
using cloudscribe.Pagination.Models;
using Microsoft.AspNetCore.Authorization;

namespace GameEx.Controllers
{
    [Authorize]
    public class RentalsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;

        public RentalsController(ApplicationDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Rentals
        public async Task<IActionResult> Index(int pageNumber=1, int pageSize=20)
        {
            int exclude = (pageNumber - 1) * pageSize;
            var user = await _userManager.GetUserAsync(User);

            var rent = await _context.Rental.Include(g => g.InventoryItem).ThenInclude(g => g.Game).OrderByDescending(o => o.DateOfRent)
               .Where(p => (p.PlayerId == user.Id || p.RenterId == user.Id) && p.IsReturned == false)
               .Skip(exclude).Take(pageSize).ToListAsync();

            var model = new List<RentalViewModel>();
            foreach (var r in rent)
            {
                var rentModel = new RentalViewModel
                {
                    GameId = r.GameId,
                    InventoryItem = r.InventoryItem,
                    IsReturned = r.IsReturned,
                    DateOfRent = r.DateOfRent,
                    DateOfReturn = r.DateOfReturn,
                    Player = r.Player,
                    PlayerId = r.PlayerId,
                    RenterId = r.RenterId,
                    Id = r.Id,
                };

                model.Add(rentModel);
            }
            var result = new PagedResult<RentalViewModel>
            {
                Data = model,
                TotalItems = _context.Rental.Include(g => g.InventoryItem).ThenInclude(g => g.Game)
                            .Where(p => (p.PlayerId == user.Id || p.RenterId == user.Id) && p.IsReturned == false).Count(),
                PageNumber = pageNumber,
                PageSize = pageSize,
            };
            ViewData["User"] = await _userManager.GetUserAsync(User);
            if (await _userManager.IsInRoleAsync(user, "Player"))
            {
                ViewData["Role"] = "Player";
            }
            else if (await _userManager.IsInRoleAsync(user, "Renter"))
            {
                ViewData["Role"] = "Renter";
            }
            return View(result);
        }

        public async Task<IActionResult> History(int pageNumber=1, int pageSize=20)
        {
            int exclude = (pageNumber - 1) * pageSize;
            var user = await _userManager.GetUserAsync(User);

            var rent = await _context.Rental.Include(g => g.InventoryItem).ThenInclude(g => g.Game).OrderByDescending(o => o.DateOfRent)
               .Where(p => p.PlayerId == user.Id || p.RenterId == user.Id)
               .Skip(exclude).Take(pageSize).ToListAsync();

            var model = new List<RentalViewModel>();
            foreach (var r in rent)
            {
                var rentModel = new RentalViewModel
                {
                    GameId = r.GameId,
                    InventoryItem = r.InventoryItem,
                    IsReturned = r.IsReturned,
                    DateOfRent = r.DateOfRent,
                    DateOfReturn = r.DateOfReturn,
                    Player = r.Player,
                    PlayerId = r.PlayerId,
                    RenterId = r.RenterId,
                    Id = r.Id,
                };

                model.Add(rentModel);
            }
            var result = new PagedResult<RentalViewModel>
            {
                Data = model,
                TotalItems = _context.Rental.Include(g => g.InventoryItem).ThenInclude(g => g.Game)
                            .Where(p => p.PlayerId == user.Id || p.RenterId == user.Id).Count(),
                PageNumber = pageNumber,
                PageSize = pageSize,
            };
            return View(result);
        }

        // GET: Rentals/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ViewBag.prevPage = Request.Headers["Referer"].ToString();

            var rental = await _context.Rental
                .Include(r => r.InventoryItem).ThenInclude(g => g.Game)
                .Include(r => r.Player)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (rental == null || _userManager.GetUserId(User) != rental.InventoryItem.RenterId 
                && await _userManager.IsInRoleAsync(await _userManager.GetUserAsync(User),"Renter"))
            {
                return NotFound();
            }

            var model = new RentalDetailsViewModel
            {
                Id = rental.Id,
                Player = await _userManager.FindByIdAsync(rental.PlayerId),
                Renter = await _context.Renter.FirstOrDefaultAsync(m => m.Id == rental.RenterId),
                InventoryItem = rental.InventoryItem,
                IsReturned = rental.IsReturned,
                DateOfRent = rental.DateOfRent,
                DateOfReturn = rental.DateOfReturn
            };


            return View(model);
        }

        // GET: Rentals/Create
        public IActionResult Create()
        {
            ViewData["GameId"] = new SelectList(_context.Set<InventoryItem>(), "RenterId", "RenterId");
            ViewData["PlayerId"] = new SelectList(_context.Player, "Id", "Id");
            return View();
        }

        // POST: Rentals/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PlayerId,RenterId,GameId,IsReturned,DateOfRent,DateOfReturn")] Rental rental)
        {
            if (ModelState.IsValid)
            {
                _context.Add(rental);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GameId"] = new SelectList(_context.Set<InventoryItem>(), "RenterId", "RenterId", rental.GameId);
            ViewData["PlayerId"] = new SelectList(_context.Player, "Id", "Id", rental.PlayerId);
            return View(rental);
        }
        // GET: Rentals/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            var rental = await _context.Rental
                .Include(r => r.InventoryItem).ThenInclude(g => g.Game)
                .Include(r => r.Player)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (rental == null)
            {
                return NotFound();
            }

            var model = new RentalDetailsViewModel
            {
                Id = rental.Id,
                Player = await _userManager.FindByIdAsync(rental.PlayerId),
                Renter = await _context.Renter.FirstOrDefaultAsync(m => m.Id == rental.RenterId),
                InventoryItem = rental.InventoryItem,
                IsReturned = rental.IsReturned,
                DateOfRent = rental.DateOfRent,
                DateOfReturn = rental.DateOfReturn
            };


            return View(model);
        }

        // POST: Rentals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var rental = await _context.Rental.FindAsync(id);
            _context.Rental.Remove(rental);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(History));
        }

        private bool RentalExists(string id)
        {
            return _context.Rental.Any(e => e.RenterId == id);
        }

        public async Task<IActionResult> Return(string id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var rental = _context.Rental.Include(r => r.InventoryItem)
                .FirstOrDefault(r => r.Id == id);
            if(rental == null)
            {
                return NotFound();
            }

            rental.IsReturned = true;
            rental.DateOfReturn = DateTime.Now;
            rental.InventoryItem.Quantity += 1;
            _context.Update(rental);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", new { id });
        }
    }
}

izvorniKod/GameEx/GameEx/Views/Rentals/Delete.cshtml
@model GameEx.ViewModels.RentalDetailsViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this rental?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">

        </dt>
        <dd class="col-sm-10">
            <img style="width:200px" src="@Model.InventoryItem.Game.PhotoUrl" />
        </dd>
        <dt class="col-sm-2">
            Game
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.InventoryItem.Game.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Player)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Player.UserName)
        </dd>
        <dt class="col-sm-2">
            Renter
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Renter.CompanyName)
        </dd>
        <dt class="col-sm-2">
            Status
        </dt>
        <dd class="col-sm-10">
            @(Model.IsReturned == true ? "Returned" : "Not returned")
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfRent)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateOfRent)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfReturn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateOfReturn)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="@Model.Player.Id" />
        <input type="hidden" asp-for="@Model.Renter.Id" />
        <input type="hidden" asp-for="@Model.InventoryItem.GameId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="History">Back to List</a>
    </form>
</div>

izvorniKod/GameEx/GameEx/Views/Rentals/Details.cshtml
@model GameEx.ViewModels.RentalDetailsViewModel
@inject Microsoft.AspNetCore.Identity.UserManager<User> _userManager
@{
    ViewData["Title"] = "Rental details";
}

<h1>Details</h1>
<div>
    <a asp-controller="Rentals" asp-action="Index" class="btn btn-outline-primary">Back to list</a>
</div>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-3">
            <img style="max-height:250px;max-width:100%" src="@Model.InventoryItem.Game.PhotoUrl" />
        </dt>
        <dd class="col-sm-7">
            <div><b>Game:</b> @Html.DisplayFor(model => model.InventoryItem.Game.Name)</div>
            <div><b>@Html.DisplayNameFor(model => model.Player):</b> @Html.DisplayFor(model => model.Player.UserName)</div>
            <div><b>Renter:</b> @Html.DisplayFor(model => model.Renter.CompanyName)</div>
            <div><b>Status:</b> @(Model.IsReturned == true ? "Returned" : "Not returned")</div>
            <div><b>@Html.DisplayNameFor(model => model.DateOfRent):</b> @Html.DisplayFor(model => model.DateOfRent)</div>
            <div><b>@Html.DisplayNameFor(model => model.DateOfReturn):</b> @Html.DisplayFor(model => model.DateOfReturn)</div>
        </dd>
    </dl>
</div>

@if (await _userManager.IsInRoleAsync(await _userManager.GetUserAsync(User), "Renter"))
{
    <div>
        <a asp-action="Return" asp-controller="Rentals" asp-route-id="@Model.Id">Game returned...</a>
    </div>
}

izvorniKod/GameEx/GameEx/Views/Rentals/History.cshtml
@model cloudscribe.Pagination.Models.PagedResult<GameEx.ViewModels.RentalViewModel>

@{
    ViewData["Title"] = "Rental history";
}

<h1>Rental history</h1>
<p>
    <div style="text-align:end">
        <a asp-action="Index" class="btn btn-outline-primary">My active rentals</a>
    </div>
</p>

<cs-pager cs-paging-pagenumber=@Model.PageNumber
          cs-paging-totalitems=@Model.TotalItems
          cs-paging-pagesize=@Model.PageSize
          cs-pagenumber-param="pageNumber"
          asp-controller="Rentals"
          asp-action="History"
          cs-pager-li-current-class="page-item active"
          cs-pager-li-other-class="page-item"
          cs-pager-li-non-active-class="page-item disabled"
          cs-pager-link-current-class="page-link"
          cs-pager-link-other-class="page-link"></cs-pager>
<table class="table">
    <thead>
        <tr>
            <th>

            </th>
            <th>
                Name
            </th>
            <th>
                Date of renting
            </th>
            <th>
                Date of return
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Data)
        {
            <tr>
                <td>
                    <img style="width:100px;height:100px" src="@item.InventoryItem.Game.PhotoUrl" />
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.InventoryItem.Game.Name)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfRent)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfReturn)
                </td>
                <td>
                    @if (item.IsReturned == true)
                    {
                    <a asp-action="Delete" asp-route-id="@item.Id" class="text-danger fa fa-trash"></a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

izvorniKod/GameEx/GameEx/Views/Rentals/Index.cshtml
@model cloudscribe.Pagination.Models.PagedResult<GameEx.ViewModels.RentalViewModel>

@{
    ViewData["Title"] = "My active rentals";
}

@{ string imgDataUrl = null;
    var byteDataImg = ViewBag.User.ProfileImage;
    if (byteDataImg != null)
    {
        string imreBase64Data = Convert.ToBase64String(byteDataImg);
        imgDataUrl = string.Format("data:image/png;base64,{0}", imreBase64Data);
    } }
@section Sidebar{
    @if (ViewBag.Role == "Player")
    {
        <div>
            <nav class="sidenav">
                <div>

                    <div class="text-center">
                        <img src="@imgDataUrl" class="avatar" />
                    </div>
                    <div class="text-center text-white">
                        <h3>@ViewBag.User.UserName</h3>
                    </div>
                    <div class="text-center text-secondary">
                        <h6>@ViewBag.User.Email</h6>
                    </div>
                </div>
                <hr />
                @if (User.Identity.Name == ViewBag.User.UserName)
                {
                    <a href="../../Identity/Account/Manage">Account settings</a>}
                <hr />
                @if (User.Identity.Name == ViewBag.User.UserName)
                {
                    <a asp-action="Index" asp-controller="Exchanges">My exchanges</a>
                    <a class="bg-secondary" asp-action="Index" asp-controller="Rentals">My rentals</a>
                    <a asp-action="Index" asp-controller="GroupInvitations">Group Invitations</a>}
                @if (User.Identity.Name == ViewBag.User.UserName)
                {
                    <a asp-action="Index" asp-controller="Groups" asp-route-id="@ViewBag.User.Id">My groups</a>}
                @if (User.Identity.Name == ViewBag.User.UserName)
                {
                    <a asp-action="Index" asp-controller="PlayerGames" asp-route-id="@ViewBag.User.Id">My collection</a>}
                <hr />
                @if (User.Identity.Name == ViewBag.User.UserName)
                {
                    <a asp-action="Create" asp-controller="PlayerGames" asp-route-id="@ViewBag.User.Id">Add game to collection</a>
                    <a asp-action="Create" asp-controller="Groups" asp-route-id="@ViewBag.User.Id">Create group</a>}
            </nav>
        </div>
    }
    else if (ViewBag.Role == "Renter")
    {
        <div>
            <nav class="sidenav">
                <div>

                    <div class="text-center">
                        <img src="@imgDataUrl" class="avatar" />
                    </div>
                    <div class="text-center text-white">
                        <h3>@ViewBag.User.UserName</h3>
                    </div>
                    <div class="text-center text-secondary">
                        <h6>@ViewBag.User.Email</h6>
                    </div>
                </div>
                <hr />
                @if (User.Identity.Name == ViewBag.User.UserName)
                {
                    <a asp-controller="InventoryItems" asp-action="Index">Inventory</a>
                    <a href="../../Identity/Account/Manage">Edit account</a>
                    <a id="edit-tab" asp-controller="Renter" asp-action="Edit" asp-route-id="@ViewBag.User.Id">Edit profile</a>
                }
                <hr />
                @if (User.Identity.Name == ViewBag.User.UserName)
                {
                    <a class="bg-secondary" asp-action="Index" asp-controller="Rentals">My rentals</a>
                }
            </nav>
        </div>

    }
}

<h1>Active rentals</h1>

<p>
    <div style="text-align:end">
        <a asp-action="History" class="btn btn-outline-primary">Rental history</a>
    </div>
</p>

<cs-pager cs-paging-pagenumber=@Model.PageNumber
          cs-paging-totalitems=@Model.TotalItems
          cs-paging-pagesize=@Model.PageSize
          cs-pagenumber-param="pageNumber"
          asp-controller="Rentals"
          asp-action="Index"
          cs-pager-li-current-class="page-item active"
          cs-pager-li-other-class="page-item"
          cs-pager-li-non-active-class="page-item disabled"
          cs-pager-link-current-class="page-link"
          cs-pager-link-other-class="page-link"></cs-pager>
<table class="table">
    <thead>
        <tr>
            <th>

            </th>
            <th>
                Name
            </th>
            <th>
                Date of renting
            </th>
            <th>
                Date of return
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Data)
        {
            <tr>
                <td>
                    <img style="width:100px;height:100px" src="@item.InventoryItem.Game.PhotoUrl" />
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.InventoryItem.Game.Name)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfRent)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfReturn)
                </td>
            </tr>
        }
    </tbody>
</table>