izvorniKod/GameEx/GameEx/Models/Game.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GameEx.Models
{
    public class Game
    {
        public string Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        [MinLength(5)]
        public string PhotoUrl { get; set; }
        public string ThumbnailUrl { get; set; }
        public string CategoryId { get; set; }
        [Required]
        [MinLength(10)]
        public string Description { get; set; }
        [Required]
        [MinLength(5)]
        public string Link { get; set; }
        [Range(0.0,5.0)]
        public double? Rating { get; set; }
        [Range(1,100)]
        public int? MinPlayers { get; set; }
        [Range(1, 100)]
        public int? MaxPlayers { get; set; }
        [Range(0, 3600)]
        public int? MinPlayingTime { get; set; }
        [Range(1, 3600)]
        public int? MaxPlayingTime { get; set; }
        public string Designer { get; set; }
        public string Publisher { get; set; }
        [Range(1900,3000)]
        public int? Year { get; set; }
        [Range(0,100)]
        public int? MinAge { get; set; }

        //za n:n vezu sa GameCategory se koristi GameCategoryGame kao sredisnja tablica koja
        //povezuje te 2 tablice
        public List<GameCategoryGame> GameCategoryGames { get; set; }
        public List<Group> Groups { get; set; }
        public List<PlayerGame> PlayerGames { get; set; }
        public List<Exchange> OfferedGames { get; set; }
        public List<Exchange> WantedGames { get; set; }
        public List<InventoryItem> InventoryItems { get; set; }
    }
}

izvorniKod/GameEx/GameEx/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GameEx.Data;
using GameEx.Models;
using cloudscribe.Pagination.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace GameEx.Controllers
{
    public class GameController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public GameController(ApplicationDbContext context, UserManager<User> userManager, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        // GET: Game
        public async Task<IActionResult> Index(int page_number = 1,int page_size=30, string query = "")
        {
            var skipNum = (page_number - 1) * page_size;
            var applicationDbContext = _context.Game
                .Include(g => g.GameCategoryGames).ThenInclude(g => g.GameCategory)
                .Where(g => g.Name.ToUpper().Contains(query.ToUpper()))
                .OrderBy(g => g.Name)
                .Skip(skipNum).Take(page_size);
            var result = new PagedResult<Game>
            {
                Data = applicationDbContext.AsNoTracking().ToList(),
                TotalItems = _context.Game
                            .Where(g => g.Name.ToUpper().Contains(query.ToUpper())).Count(),
                PageNumber = page_number,
                PageSize = page_size
            };

            var user = await _userManager.GetUserAsync(User);
            IList<string> roles = null;
            if(user != null)
            {
                roles = await _userManager.GetRolesAsync(user);
            }
            if(roles != null)
            {
                ViewData["Roles"] = roles;
            }
            
            return View(result);
        }

        // GET: Game/Details/5
        [Route("Game/{id}")]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Game
                .Include(g => g.GameCategoryGames).ThenInclude(g => g.GameCategory)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (game == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(User);
            IList<string> roles = null;
            if (user != null)
            {
                roles = await _userManager.GetRolesAsync(user);
            }
            if (roles != null)
            {
                ViewData["Roles"] = roles;
            }

            return View(game);
        }

        // GET: Game/Create
        [Authorize(Roles= "Moderator,Administrator")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Game/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Moderator,Administrator")]
        public async Task<IActionResult> Create([Bind("Id,Name,PhotoUrl,ThumbnailUrl,Description,Link,MinPlayers,MaxPlayers,MinPlayingTime,MaxPlayingTime,Designer,Publisher,Year,MinAge")] Game game)
        {
            ModelState.Clear();

            game.Id = Guid.NewGuid().ToString();
            TryValidateModel(game);
            if (ModelState.IsValid)
            {
                _context.Add(game);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(game);
        }

        // GET: Game/Edit/5
        [Authorize(Roles = "Moderator,Administrator")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Game.Include(g => g.GameCategoryGames)
                    .ThenInclude(gcg => gcg.GameCategory)
                .Where(g => g.Id == id).FirstOrDefaultAsync();
            if (game == null)
            {
                return NotFound();
            }
            return View(game);
        }

        // POST: Game/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Moderator,Administrator")]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name,PhotoUrl,ThumbnailUrl,CategoryId,Description,Link,MinPlayers,MaxPlayers,MinPlayingTime,MaxPlayingTime,Designer,Publisher,Year,MinAge")] Game game)
        {
            if (id != game.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var gameDb = _context.Game.AsNoTracking().Where(g => g.Id == id).FirstOrDefault();
                    if(gameDb != null)
                    {
                        game.Rating = gameDb.Rating;
                    }
                    _context.Update(game);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GameExists(game.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(game);
        }

        // GET: Game/Delete/5
        [Authorize(Roles = "Moderator,Administrator")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Game
                .Include(g => g.GameCategoryGames).ThenInclude(g => g.GameCategory)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (game == null)
            {
                return NotFound();
            }

            return View(game);
        }

        // POST: Game/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Moderator,Administrator")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var game = await _context.Game.FindAsync(id);
            _context.Game.Remove(game);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public List<Game> Api(string term)
        {
            return _context.Game.Where(g => g.Name.ToUpper().Contains(term.ToUpper())).Take(10).ToList();
        }

        private bool GameExists(string id)
        {
            return _context.Game.Any(e => e.Id == id);
        }
    }
}

izvorniKod/GameEx/GameEx/Views/Game/Create.cshtml
@model GameEx.Models.Game

@{
    ViewData["Title"] = "Create game";
    List<CheckboxModel> checkboxCategoryData = ViewBag.CategoryId;
    Layout = "/Views/Shared/_Layout.cshtml";
}

<h1>New game</h1>

<hr />

<div class="row">
    <div class="col-12">
        <form asp-action="Create" class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group col-12">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group col-12">
                <label asp-for="Description" class="control-label">Description (Allowed as HTML):</label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group col-12">
                <label asp-for="Link" class="control-label">Official page URL:</label>
                <input asp-for="Link" class="form-control" />
                <span asp-validation-for="Link" class="text-danger"></span>
            </div>
            <div class="form-group col-12">
                <label asp-for="PhotoUrl" class="control-label">Photo URL:</label>
                <input asp-for="PhotoUrl" class="form-control" />
                <span asp-validation-for="PhotoUrl" class="text-danger"></span>
            </div>
            <div class="form-group col-12">
                <label asp-for="ThumbnailUrl" class="control-label">Thumbnail URL:</label>
                <input asp-for="ThumbnailUrl" class="form-control" />
                <span asp-validation-for="ThumbnailUrl" class="text-danger"></span>
            </div>
            <div class="form-group col-12 col-md-6">
                <label asp-for="MinPlayers" class="control-label">Players:</label>
                <div class="input-group">
                    <input asp-for="MinPlayers" class="form-control" placeholder="Min" />
                    <input asp-for="MaxPlayers" class="form-control" placeholder="Max" />
                </div>
                <span asp-validation-for="MinPlayers" class="text-danger"></span>
                <span asp-validation-for="MaxPlayers" class="text-danger"></span>
            </div>
            <div class="form-group col-12 col-md-6">
                <label asp-for="MinPlayingTime" class="control-label">Playing time:</label>
                <div class="input-group">
                    <input asp-for="MinPlayingTime" class="form-control" placeholder="Min" />
                    <input asp-for="MaxPlayingTime" class="form-control" placeholder="Max" />
                </div>
                <span asp-validation-for="MaxPlayingTime" class="text-danger"></span>
                <span asp-validation-for="MinPlayingTime" class="text-danger"></span>
            </div>
            <div class="form-group col-12 col-md-6">
                <label asp-for="Designer" class="control-label">Designer:</label>
                <input asp-for="Designer" class="form-control" />
                <span asp-validation-for="Designer" class="text-danger"></span>
            </div>
            <div class="form-group col-12 col-md-6">
                <label asp-for="Publisher" class="control-label">Publisher:</label>
                <input asp-for="Publisher" class="form-control" />
                <span asp-validation-for="Publisher" class="text-danger"></span>
            </div>
            <div class="form-group col-12 col-md-6">
                <label asp-for="Year" class="control-label">Year of publishing:</label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group col-12 col-md-6">
                <label asp-for="MinAge" class="control-label">Minimum required age:</label>
                <input asp-for="MinAge" class="form-control" />
                <span asp-validation-for="MinAge" class="text-danger"></span>
            </div>
            <div class="col-12">
                <hr />
            </div>
            <div class="form-group col-4">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-outline-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

izvorniKod/GameEx/GameEx/Views/Game/Delete.cshtml
@model GameEx.Models.Game

@{
    ViewData["Title"] = "Delete game";
    Layout = "/Views/Shared/_Layout.cshtml";
}
<h3>Are you sure you want to delete this game?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">

        </dt>
        <dd class="col-sm-10">
            <img height="150px" src="@Html.DisplayFor(model => model.PhotoUrl)" />
        </dd>
        <dt class="col-sm-2">
            Categories:
        </dt>
        <dd class="col-sm-10">
            @foreach (var cat in Model.GameCategoryGames)
            {
                @(cat.GameCategory.Name)<br />
            }

        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.Raw(@Model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Link)
        </dt>
        <dd class="col-sm-10">
            <a href="@Html.DisplayFor(model => model.Link)">@Html.DisplayFor(model => model.Link)</a>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class="col-sm-10">
            @{
                int? rating = null;
                if (Model.Rating != null)
                {
                    rating = (int)(Model.Rating / 5 * 100);
                }
                var background = "";

                if (rating < 100 && rating >= 75)
                {
                    background = "bg-success";
                }
                else if (rating < 75 && rating >= 50)
                {
                    background = "bg-warning";
                }
                else if (rating < 50)
                {
                    background = "bg-danger";
                }
                else
                {
                    background = "bg-secondary";
                }
            }

            <span class="@background text-white text-center font-weight-bold p-2"
                  style="font-size:2rem;">
                @(rating == null ? "N/A": rating.ToString())
            </span>
        </dd>

        <dt class="col-sm-2">
            No. of players:
        </dt>
        <dd class="col-sm-10">
            @if (Model.MinPlayers != null && Model.MaxPlayers != null)
            {
                <span>@Model.MinPlayers-@Model.MaxPlayers</span>
            }
            else
            {
                <span>N/A</span>
            }

        </dd>
        <dt class="col-sm-2">
            Playing time:
        </dt>
        <dd class="col-sm-10">
            @if (Model.MinPlayingTime != null && Model.MaxPlayingTime != null)
            {
                <span>@Model.MinPlayingTime min - @Model.MaxPlayingTime min</span>
            }
            else
            {
                <span>N/A</span>
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Designer)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Designer)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Publisher)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class="col-sm-2">
            Ages:
        </dt>
        <dd class="col-sm-10">
            @(Model.MinAge + "+") 
        </dd>
        <dt class="col-sm-2">
            Categories:
        </dt>
        <dd class="col-sm-10">
            @foreach (var item in Model.GameCategoryGames)
            {
                @(item.GameCategory.Name + " ")

            }

        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-outline-secondary">Back</a>
    </form>
</div>

izvorniKod/GameEx/GameEx/Views/Game/Details.cshtml
@model GameEx.Models.Game

@{
    ViewData["Title"] = Model.Name;
    Layout = "_Layout.cshtml";
    List<string> roles = null;
    if (ViewBag.Roles != null)
    {
        roles = ViewBag.Roles;
    }

}


<div class="mt-4">
    <div class="black-box align-items-center d-flex">
        <div class="container d-flex align-items-center">
            <div class="polaroid">
                <img height="300px" src="@Model.PhotoUrl" />
            </div>
            <div class="flex-grow-1 p-6">
                <div class="text-white p-6 row">
                    <div class="col-3">

                    </div>
                    <div class="col-6 text-center">
                        <h3>@Model.Name</h3>
                        <span>@Html.DisplayFor(model => model.Publisher)</span>
                    </div>
                    <div class="col-3">
                        <div>
                            @{
                                int? rating = null;
                                if (Model.Rating != null)
                                {
                                    rating = (int)(Model.Rating / 5 * 100);
                                }
                                var background = "";

                                if (rating < 100 && rating >= 75)
                                {
                                    background = "bg-success";
                                }
                                else if (rating < 75 && rating >= 50)
                                {
                                    background = "bg-warning";
                                }
                                else if (rating < 50)
                                {
                                    background = "bg-danger";
                                }
                                else
                                {
                                    background = "bg-secondary";
                                }
                            }

                            <span class="@background text-white text-center font-weight-bold p-2"
                                  style="font-size:2rem;">
                                @(rating == null ? "N/A": rating.ToString())
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="container text-left">
        <dl class="row">
            <dt class="col-sm-2">
                Categories:
            </dt>
            <dd class="col-sm-10">
                @foreach (var item in Model.GameCategoryGames)
                {
                    @(item.GameCategory.Name + " ")

                }

            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.Raw(Model.Description)
            </dd>
            <dt class="col-sm-2">

            </dt>
            <dd class="col-sm-10">
                <a href="@Model.Link">More info...</a>
            </dd>

            <dt class="col-sm-2">
                No. of players:
            </dt>
            <dd class="col-sm-10">
                @if (Model.MinPlayers != null && Model.MaxPlayers != null)
                {
                    <span>@Model.MinPlayers-@Model.MaxPlayers</span>
                }
                else
                {
                    <span>N/A</span>
                }

            </dd>
            <dt class="col-sm-2">
                Playing time:
            </dt>
            <dd class="col-sm-10">
                @if (Model.MinPlayingTime != null && Model.MaxPlayingTime != null)
                {
                    <span>@Model.MinPlayingTime min - @Model.MaxPlayingTime min</span>
                }
                else
                {
                    <span>N/A</span>
                }
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Designer)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Designer)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Year)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Year)
            </dd>
            <dt class="col-sm-2">
                Ages:
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.MinAge) +
            </dd>


        </dl>
        <div>
            @if (roles != null && (roles.Contains("Moderator") || roles.Contains("Administrator")))
            {
                <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-success">Edit</a>
            }

            <a asp-action="Index" class="btn btn-secondary">Back to List</a>
        </div>
    </div>

</div>
<div style="height:50px;">

</div>

izvorniKod/GameEx/GameEx/Views/Game/Index.cshtml
@model cloudscribe.Pagination.Models.PagedResult<GameEx.Models.Game>
 
@{
    ViewData["Title"] = "All games";
    Layout = "/Views/Shared/_Layout.cshtml";
    List<string> roles = null;
    if(ViewBag.Roles != null)
    {
        roles = ViewBag.Roles;
    }

}

<h1>All games</h1>

@if(roles != null && (roles.Contains("Moderator") || roles.Contains("Administrator")))
{
<p>
    <a asp-action="Create">Add new game...</a>
</p>
}
<div class="row">
    <div class="col-4">
        <form asp-action="Index" method="get" class="form-group input-group">
            <input type="text" name="query" class="form-control"/>
            <button type="submit" class="btn btn-primary input-group-append d-flex align-items-center"><i class="fa fa-search"></i></button>
        </form>
    </div>
    <div class="col-8"></div>
    <cs-pager cs-paging-pagenumber="Model.PageNumber"
              cs-paging-totalitems="Model.TotalItems"
              cs-paging-pagesize="Model.PageSize"
              cs-pagenumber-param="page_number"
              asp-controller="Game"
              asp-action="Index"
              cs-pager-li-current-class="page-item active"
              cs-pager-li-other-class="page-item"
              cs-pager-li-non-active-class="page-item disabled"
              cs-pager-link-current-class="page-link"
              cs-pager-link-other-class="page-link">
    </cs-pager>

    <table class="table table-hover">
        <thead>
            <tr>
                <th>

                </th>
                <th style="width:20%;">
                    Name
                </th>
                <th>
                    Rating
                </th>
                <th>
                    Players
                </th>
                <th style="width:15%;">
                    Playing time
                </th>
                <th>
                    Publisher
                </th>
                <th>
                    Year
                </th>
                <th>
                    Age
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Data)
            {
                <tr>
                    <td>
                        <img width="100px" height="100px" src="@item.PhotoUrl" />
                    </td>
                    <td style="width:20%;">
                        <a asp-action="Details" asp-route-id="@item.Id">
                            @Html.DisplayFor(modelItem => item.Name)
                        </a>

                    </td>
                    <td>
                        @{
                            int? rating = null;
                            if (item.Rating != null)
                            {
                                rating = (int)(item.Rating / 5 * 100);
                            }
                            var background = "";

                            if (rating < 100 && rating >= 75)
                            {
                                background = "bg-success";
                            }
                            else if (rating < 75 && rating >= 50)
                            {
                                background = "bg-warning";
                            }
                            else if (rating < 50)
                            {
                                background = "bg-danger";
                            }
                            else
                            {
                                background = "bg-secondary";
                            }
                        }
                        @if (rating != null)
                        {
                            <span class="@background text-white text-center font-weight-bold p-2"
                                  style="font-size:2rem;">
                                @(rating.ToString())
                            </span>
                        }
                        else
                        {
                            <span class="@background text-white text-center font-weight-bold p-2"
                                  style="font-size:1.5rem;">
                                N/A
                            </span>
                        }

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MinPlayers)
                        -
                        @Html.DisplayFor(modelItem => item.MaxPlayers)
                    </td>
                    <td style="width:15%;">
                        @(item.MinPlayingTime == null? "": item.MinPlayingTime + " min -")
                        @(item.MaxPlayingTime == null? "": item.MaxPlayingTime + " min")
                    </td>
                    <!--<td>
                        @Html.DisplayFor(modelItem => item.Designer)
                    </td>-->
                    <td>
                        @Html.DisplayFor(modelItem => item.Publisher)
                    </td>
                    <td class="text-right">
                        @Html.DisplayFor(modelItem => item.Year)
                    </td>
                    <td class="text-right">
                        @(item.MinAge == null? "": item.MinAge + "+")
                    </td>
                    <td>
                        @if (roles != null && (roles.Contains("Moderator") || roles.Contains("Administrator")))
                        {
                            <div class="text-center">
                                <a asp-action="Edit" asp-route-id="@item.Id" class="text-success fa fa-edit"></a>
                            </div>
                            <div class="text-center">
                                <a asp-action="Delete" asp-route-id="@item.Id" class="text-danger fa fa-trash"></a>
                            </div>
                        }

                        <div class="text-center">
                            <a href="@(item.Link != null? item.Link: "")" class="fa fa-info"></a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <cs-pager cs-paging-pagenumber="Model.PageNumber"
              cs-paging-totalitems="Model.TotalItems"
              cs-paging-pagesize="Model.PageSize"
              cs-pagenumber-param="page_number"
              asp-controller="Game"
              asp-action="Index"
              cs-pager-li-current-class="page-item active"
              cs-pager-li-other-class="page-item"
              cs-pager-li-non-active-class="page-item disabled"
              cs-pager-link-current-class="page-link"
              cs-pager-link-other-class="page-link">

    </cs-pager>
</div>